### ISSUE TITLE
Sample projects BUGs

### ISSUE THREAD

**Issue by neoneper** [McManning/BlueGraph#33]
Hi MC:
All examples have problems with the node connection. They do not connect from edges to another nodes! 
All ports at nodes are invalid to drag drop edge!

**Comment by neoneper** [comment]
I took a quick look at "`CanvasView`" and noticed that you are not implementing the virtual method "`GetCompatiblePorts`". I believe this could be the problem. I'm starting today with your project, and I intend to be a contributor to the repository. I'm taking an overall look at everything to understand how it all works. I still don't understand the reason for using the tags. Initially I thought it was just to filter the connections allowed to the ports. But I think I'm wrong. Can you give me a light?

**Comment by McManning** [comment]
Hi neoneper, 

The master branch isn't up to date with my local copy. I think I've pushed some changes to the samples without the rest of my changes. I'll take some time tomorrow morning to get this repo as up to date with what I'm working with. 

For tags - it's to restrict which `Node` implementation classes are available for specific Graphs. If you have an application with 2+ different types of graphs (e.g. one for dialog trees and another for procedural content generating) you can use tags to ensure nodes can only be instantiated used on their relevant graphs. 

I have some documentation on tags here: https://github.com/McManning/BlueGraph/wiki/Node-Attributes#tags-attribute

**Comment by McManning** [comment]
I've updated master with what I had. I've also split samples into their own project so it's a bit easier to work with: https://github.com/McManning/BlueGraph-Samples
