### ISSUE TITLE
BUG - Null Canvas

### ISSUE THREAD

**Issue by neoneper** [McManning/BlueGraph#36]
If I close the unity with an open Graph and then re-open the unity, the canvas of the Graph will be null in her GraphEditorWindows.
**GraphEditorWindow Line 33:**
`
        protected virtual void Update()
        {
            Canvas.Update(); //Canvas is NULL
        }`

`NullReferenceException: Object reference not set to an instance of an object
BlueGraph.Editor.GraphEditorWindow.Update () (at Assets/BlueGraph/BlueGraph-Master/Editor/GraphEditorWindow.cs:33)
UnityEditor.HostView.SendUpdate () (at <67055f1be3654e2a987254d5437ee5b8>:0)
UnityEditor.EditorApplication.Internal_CallUpdateFunctions () (at <67055f1be3654e2a987254d5437ee5b8>:0)`

![image](https://user-images.githubusercontent.com/12010067/93690368-d4851880-faad-11ea-9043-548196b699cc.png)

I just tried to create a condition to reload the chart if it is null, but I was unsuccessful.

**Comment by neoneper** [comment]
I noticed that this problem also occurs if you have an open Graph and then update a buggy script. When unity updates the Graph it will bug

**Comment by McManning** [comment]
Was resolved by one of the commits in #41
