### ISSUE TITLE
Ideas for New Attributes

### ISSUE THREAD

**Issue by neoneper** [McManning/BlueGraph#40]
**Graph Attributes:**
- RequireNode(type): Used at graph, Automatically create a specified type node if none exists.
- RequireOnce(type): Used at graph, It will create a node of the specified type if none exist and automatically prevent new nodes of the same type at the search provider.

**Node Attributes:**
Include Moveable(bool) at NodeAttribute:  allow or deny move node at graph.

**Comment by McManning** [comment]
`RequireNode` and `Moveable` were merged through #41 . 

I think `RequireOnce` can be best handled by using `RequireNode` combined with just tagging the node in a way where it doesn't show up in the default search provider (I typically use `[Tags("Hidden")]` for nodes like that).

**Comment by McManning** [comment]
Going to call this closed since it was mostly resolved by #41 and the above suggestion.
