### ISSUE TITLE
Empty References Bug

### ISSUE THREAD

**Issue by neoneper** [McManning/BlueGraph#42]
**BUG**
When the graph is serialized, any null reference from node or port, used by the user in nodes or graphs will cause errors.

**To Reproduce**
1. Create a empty variable for Port, at some Node, Sample: 
`Port cacheInPort;`

2. Open the graph and create the Node that have this empty reference.
3. With the graph oppened yet, open theScriptEditor and update somethink and then save it. 
4. Return to unity and wait it refresh.

**Screenshots**
 - Empty Port Variable:
![image](https://user-images.githubusercontent.com/12010067/94326315-8bcfd280-ff79-11ea-9068-70c10e27a911.png)
 - Node with empty portVariable at graph:
![image](https://user-images.githubusercontent.com/12010067/94326348-b588f980-ff79-11ea-8a54-501b64701b83.png)
- Update some script and refresh unity:
![image](https://i.gyazo.com/c5c59439a906a143ea14e0abc17e7f1a.gif)

**Follow the Error**.
 - Port.cs
![image](https://user-images.githubusercontent.com/12010067/94326456-5bd4ff00-ff7a-11ea-80f6-b655a6a057c4.png)

**Comment by McManning** [comment]
I'm going to close this one by suggesting you use the `Node.GetPort()` method. It should be sufficiently fast now without having to store an additional reference.

I can't confidently recommend maintaining additional references to ports - as the editor may create/destroy instances while someone is editing connections. The safest route is to just use GetPort() when a port is actually needed - as it'll ensure everything was deserialized safely.
