### ISSUE TITLE
After restarting Unity 2021.2, graph loads missing data

### ISSUE THREAD

**Issue by jsm174** [McManning/BlueGraph#51]
**Describe the bug**

When I create a graph, close unity, and come back to work later, the graph loads and data is missing data.

**To Reproduce**

1) Create graph
2) Open graph
3) Add a node 
4) Save Project
5) Close Unity
6) Open Unity
7) Open graph
8) Graph nodes are missing values

**Expected behavior**

Graph should load with same connections and properties accessible

**Screenshots**

![Screen Shot 2021-12-03 at 8 08 55 AM](https://user-images.githubusercontent.com/1197137/144607751-5a79925e-b575-4b54-877d-20d9f9472911.png)

Close and restart:

![Screen Shot 2021-12-03 at 8 10 55 AM](https://user-images.githubusercontent.com/1197137/144608028-5430ec4f-37f1-4b02-ab9f-419f61a6c4f6.png)

**Platform (please complete the following information):**
 - Unity Version 2021.2.4f1
 - BlueGraph Version v1.0

**Comment by McManning** [comment]
I've tested this on 2021.2.5f1 (closest official release currently available through the hub) using a clean copy of the BlueGraph-Samples project and can't seem to reproduce the issue.

I am noticing that your initial graph isn't rendering the custom USS that came with that sample - e.g it should have looked like:

![image](https://user-images.githubusercontent.com/1057607/145425016-d33d11c1-6d64-44d9-86fb-284b9ce66b03.png)

So there seems to be more than just an issue while reloading the editor. 

Few questions to help me narrow this down further:

1. Any sort of errors in the console when you create a new graph / edit a graph / re-open a graph?
1. How did you setup this project - did you copy the Execution Flow sample code into a pre-existing project or are you just running the samples project?
2. What changes have you made to the sample code? (Some code snippets would be helpful here, if possible)

I'll see if I can pull down a copy of  2021.2.4f1 and test that as well. I'm not seeing anything in Unity's changelog for the .5f1 that seem relevant but there may have been some hidden changes I'm not seeing.

**Comment by McManning** [comment]
Just omitting the USS shouldn't break the actual graph when reloading the editor. So I'm suspecting something else might be a problem.

If Bolt works for you - great! If you do run into some use cases that don't seem to fit with Bolt, let me know. I'd love to be able to expand the samples project with some more variations on how the framework can be used.

**Comment by jsm174** [comment]
Sorry it took so long, had to get everything set up. I invited you to this project.

https://github.com/jsm174/vpe_rock_project/tree/feature/nodegraph

Under usage, there are a bunch of steps. Should be able to copy and paste. You'll need to do that before opening the Unity project.

**Comment by McManning** [comment]
Thanks, I can replicate the issue. It looks like node constructors are now being called when the inspector deserializes SerializeReference objects - which breaks some port mapping logic I have setup to run whenever deserialization happens. This should be an easy fix. 

Thanks for all your help at tracking this one down!

**Comment by jsm174** [comment]
Great. Thanks for looking into this! We really appreciate it!
